### PR TITLE
docker opts tweak

### PR DESCRIPTION
**Pull request by nicolasmure**
Hi,

First of all thanks for sharing this and your slides of sfLive2015 :+1: 
I tried to setup this dev env on my machine but I had some troubles with the docker0 interface changing its IP address at every startup.
Finally, I figured it out by following [this instruction](https://github.com/tonistiigi/dnsdock#setup).
That's why I propose to include the solution into your readme file.

By the way, I had performance troubles even with activating the docker service this way :

``` bash
sudo update-rc.d docker enable
```

but replacing the `enable` instruction with `defaults` looks to have solved my problem.
I can make a PR for this too if you wish.

For info, I'm running on Ubuntu Gnome 15.04, linux 4.2.0, docker 1.8.3, docker-compose 1.4.2 .

### CODE REVIEW

**Comment by nicolasmure** [comment]
Hello,

actually, changing the `sudo update-rc.d docker enable` to `defaults` has't resolved my DNS resolving performance issue (for browsing the Internet, and also browsing the dev project).
Apparently, there are [recommendations](https://docs.docker.com/articles/systemd/) indicating to use a `systemctl enable docker` command with systemd. Even with this, I still have DNS slow-downs when the dns-gen container is running.

Does my problem has anything to see with the [`-d`](https://github.com/jderusse/docker-dns-gen/blob/master/config/supervisord.conf#L7) option which may be contradictory with the `-k` option? Does only the `-k` option isn't good enough (foreground process and no debug)?
Does some of you also have slow-downs when the dns-gen container is running? Is it because of the dnsmasq server not being efficient enough?

Any help is appreciated :wink: 

Thanks

**Comment by nicolasmure** [comment]
Mmm, things appear to look better if I add this to my docker-compose.yml file under the web server container section :

``` yaml
dns:
    - 172.17.42.1
```

([source](https://github.com/docker/compose/issues/356) and [source](https://github.com/docker/compose/pull/325))
and if I empty the `/etc/resolv.conf` file on the running dns-gen container.

I have to keep the dns-gen container running to be able to access to the webserver container by a domain name (eg http://dev.myapp.com/ ).
Does it is the docker0 interface who causes troubles?

Doing so, the problem is that the `/etc/resolv.conf` files always come back with the `nameserver 172.17.42.1` line when I restart the dns-gen  container...

**Comment by nicolasmure** [comment]
After some additional searches and tries, it looks like my DNS resolution is working just by emptying the `/etc/resolv.conf` file on the running dns-gen container. I don't have to provide the dns option in my docker-compose file.

Does someone has experienced the same issue?
Any hints about how to keep the `/etc/resolv.conf` file empty on the dns-gen container?

**Comment by nicolasmure** [comment]
In fact, the performance problem seems to come from the dns-sync container.
If I don't use it, I don't encounter the problem (same on the machine of my colleague).
So we're just using the dns-gen container :wink:

**Comment by jderusse** [comment]
Thank you, for your feedback.

In fact, I dont use dns-sync anymore, I replace it by a local dns-masq server (directly installed on the host) which forward the resolution to the dns-gen container when the TLD ends with `.docker`. It works great, but I've to clearly explains it in the readme.

Here is my conf:
0) host configured to used a local dns-masq server (default in debian 9 and lasts ubuntu)
1) docker configured to always use the same DNS Server (which is docker0 interface)

```
# /etc/default/docker
DOCKER_OPTS="--dns=172.17.42.1 --bip=172.17.42.1/24"
```

2) dns-gen configured to forward listen on port 54 on the hosts (you'll see why after)

```
docker run -d --name dns-gen --restart always -p 54:53/udp -v /var/run/docker.sock:/var/run/docker.sock jderusse/dns-gen
```

3) local dns-masq configured to listen on interface lo (127.0.0.1) and docker0 (172.17.42.1) and forward traffic to dns-gen (throught the port forwarding on port54) when tld is `.docker`

```
# /etc/NetworkManager/dnsmasq.d/01_docker`
bind-interfaces
interface=lo
interface=docker0

server=/docker/127.0.0.1#54
```

Thank to this configuration:
- When the `host` want to resolve `google.com` the workflow is `host` -> `dns-masq` -> `external dns`
- When the `host` want to resolve `foo.docker` the workflow is `host` -> `dns-masq` -> `127.0.0.1:54` -> `dns-gen`
- When a `container` want to resolve `google.com` the workflow is `container` -> `172.17.42.1` -> `dns-masq` -> `external dns`
- When a `container` want to resolve `foo.docker` the workflow is `container` -> `172.17.42.1` -> `dns-masq` -> `127.0.0.1:54` -> `dns-gen`

It's a little bit weird, but the only one solution which works for every cases.

BUT there is an infinit loop in this workflow when the tld ends with `.docker` and `dns-gen` can't resolve the DNS (the container does not exists for instance), it forward the request to the container's OS which is configured (as evry others containers) to forward the request to the docker0 interface. 
The workflow is
`dns-gen` -> `172.17.42.1` -> `dns-masq` -> `127.0.0.1:54` -> `dns-gen` -> `172.17.42.1` -> ...

To fix it, you juste have to :
5) Disabled self-resolution in dns-gen why erasing content of /etc/resolv.conf

```
docker exec -ti dns-gen sh -c "echo > /etc/resolv.conf"
```

The workflow is now
`dns-masq` -> `127.0.0.1:54` -> `dns-gen` -> error

**Comment by nicolasmure** [comment]
Thank you for your detailed answer :+1:

**Pull request merged**
